import { Injectable } from '@angular/core';

@Injectable()
export class Globals {
  postSet: string[] = [
    'Athani',
    'Devakottai',
    'Irandampulikadu',
    'Kalagam',
    'Kalanivasal',
    'Kalathur',
    'Kalluranikadu',
    'Karambakadu',
    'Karuppamanai',
    'Kuruvikarambai',
    'Mallipattinam',
    'Manakadu',
    'Mangalanadu',
    'Marungapallam',
    'Mavadukurichi',
    'Mudachikadu',
    'Mudhukadu',
    'Nadiyam',
    'Paingal',
    'Pattukottai',
    'Peravurani',
    'Perumagalur',
    'Pookkollai',
    'Rudrachinthamani',
    'Serubalakadu',
    'Sethubhavachatram',
    'Udayanadu',
    'Veeraiyankottai',
    'Vilangulam',
  ];
  nameSet: string[] = [
    'Aishamariam',
    'Aiyakannu',
    'Aiyasamy',
    'Akilan',
    'Alagammal',
    'Alagappan',
    'Alagesan',
    'Allapichai',
    'Amaravathi',
    'Amina',
    'Aminabayham',
    'Amirtham',
    'Amsavalli',
    'Amutha',
    'Anand',
    'Anandhan',
    'Anandhi',
    'Anbarasan',
    'Ansammal',
    'Anthonyraj',
    'Appadurai',
    'Appas',
    'Apthul Ageis',
    'Apthulbarkath',
    'Apthulmagis',
    'Arasilankumari',
    'Arasu',
    'Aravind',
    'Arjunan',
    'Arumugam',
    'Arumugam lic',
    'Arunagiri',
    'Athmanathan',
    'Avidai',
    'Ayyappan',
    'Ayyathurai',
    'Baby',
    'Balan',
    'Balasubramaniam',
    'Balu',
    'Banu',
    'Banumathi',
    'Barathi',
    'Barjanu',
    'Baskar',
    'Bhagyalaxmi',
    'Bharagathali',
    'Bhuvaneswari',
    'Bose',
    'Bragathnisha',
    'C/O,Eliyash shoomart,',
    'Chandirarasu',
    'Chandran',
    'Chandrasekar',
    'Chelladurai',
    'Chellammal',
    'Chidambaram',
    'Chinnaiya',
    'Chinnakannu',
    'Chinnankonar',
    'Chinnasamy',
    'Chinnathambi',
    'Chitra',
    'Dange',
    'Devendran',
    'Dhanalaxmi',
    'Dhanapriya',
    'Dharmaraju',
    'Duraiarasan',
    'Duraisamy',
    'Durgadevi',
    'Ehambaram',
    'Eilango',
    'Eilangovan',
    'Eilayaraja',
    'Farooq',
    'Ganapathy',
    'Ganesan',
    'Gayathiri',
    'Gnanam',
    'Gnanaprakasam',
    'Gokul',
    'Gopi',
    'Govindan',
    'Govindaraj',
    'Govindaraju',
    'Gunalan',
    'Gunasekar',
    'Gunasekaran',
    'Gunasundari',
    'Haji alima',
    'Hariharan',
    'Ibramsha',
    'Iyappan',
    'Jagadeesan',
    'Jaganathan',
    'Jaherusen',
    'Jailavudeen',
    'Jaisankar',
    'James',
    'Jasmine',
    'Jayachitra',
    'Jayam',
    'Jayaprkash',
    'Jayaraman',
    'Jayendaran',
    'Jeevanantham',
    'Jinna',
    'Jiyavudeen',
    'Jothi',
    'Kabeer mohamed',
    'Kailasam',
    'Kala',
    'Kalaiselvan',
    'Kalaivanan',
    'Kalidas',
    'Kalimuthu',
    'Kaliyammal',
    'Kaliyamoorthi',
    'Kamalakannan',
    'Kamaludeen',
    'Kamaraj',
    'Kamatchi',
    'Kannagi',
    'Kannaiyan',
    'Kannan',
    'Karthiga',
    'Karthik',
    'Karthika',
    'Karthikeyan',
    'Karunakaran',
    'Karuppaian',
    'Karuppaiya',
    'Kasinathan',
    'Kasiyappan',
    'Kasthuri',
    'Kataiyan',
    'Kathaian',
    'Katharsa',
    'Kavitha',
    'Kayambu',
    'Kesavan',
    'Kumar',
    'Kumaravel',
    'Kunju',
    'Kuthan',
    'Kuttiambalam',
    'Kuttiyappan',
    'Lailathul',
    'Lakshmi',
    'Latha',
    'Laxmanan',
    'M.K.Panneerselvam',
    'Madhiyalagan',
    'Mahadevi',
    'Mahalingam',
    'Maheswari',
    'Maithili',
    'Mala',
    'Malaikkannan',
    'Malar',
    'Malliga',
    'Mangai',
    'Mangalam',
    'Mangalam sister',
    'Mangayarkarasi',
    'Mani',
    'Manikam',
    'Manikandan',
    'Manimaran',
    'Manimekalai',
    'Manoharan',
    'Marimuthu',
    'Mariyappan',
    'Marrikannu',
    'Marrimuthu',
    'Maruthambal',
    'Maruthamuthu',
    'Masila',
    'Masilamani',
    'Masthangani',
    'Meena',
    'Meharajgani',
    'Meiyanathan',
    'Meiyar',
    'Mohamed Meeran',
    'Mohamed maideen',
    'Mohamed ravuthar',
    'Mohamed salim',
    'Mohamedapthulla',
    'Mohamedravuthar',
    'Mohamedsirasudeen',
    'Mohan',
    'Moorthy',
    'Mugundhan',
    'Mumdajbegam',
    'Mumtaj',
    'Mundaiyan',
    'Muniyandi',
    'Muniyasamy',
    'Murugaiyan',
    'Murugan',
    'Muruganatham',
    'Murugesan',
    'Muthaiya',
    'Muthaiyan',
    'Muthalippu',
    'Muthu',
    'Muthudurai',
    'Muthukaruppan',
    'Muthulaxmi',
    'Muthumarri',
    'Muthuveeran',
    'Nadesan',
    'Nadimuthu',
    'Nagalingam',
    'Nagan',
    'Nagarajan',
    'Nagendran',
    'Naguran',
    'Nagurgani',
    'Nandakumar',
    'Nathiya',
    'Navaneethan',
    'Navasgan',
    'Neela',
    'Neelakandan',
    'Neelamurugan',
    'Neelapriya',
    'Neelavathi',
    'Neelaveni',
    'Neelkandan',
    'Nithishkumar',
    'Noor mohamed',
    'Padmini',
    'Pakkirisamy',
    'Palanisamy',
    'Palanivel',
    'Palraj',
    'Palsamy',
    'Panchatsaram',
    'Pandi',
    'Pandian',
    'Pandiyammal',
    'Panjavarnam',
    'Panneer',
    'Panneerselvam',
    'Paramasivam',
    'Parvathi',
    'Pathar nisha',
    'Pavithira',
    'Peramaiyan',
    'Peraman',
    'Peramanathan',
    'Perumal',
    'Pichai',
    'Pichaiyan',
    'Ponnan',
    'Ponnusamy pillai',
    'Poongothai',
    'Praba',
    'Prabu',
    'Priya',
    'Puvaneswari',
    'Radhakrishnan',
    'Raja',
    'Rajagopal',
    'Rajakannu',
    'Rajamanikam',
    'Rajan',
    'Rajani',
    'Rajathi',
    'Rajendran',
    'Rajeswari',
    'Rajini',
    'Rajudevar',
    'Ramachandran',
    'Ramaiah',
    'Ramaiyan',
    'Ramamoorthi',
    'Raman',
    'Ramanathan',
    'Ramanujam',
    'Ramesh',
    'Ramjanbegam',
    'Ramu',
    'Ramukannu',
    'Ramuthaee',
    'Rani',
    'Ranjani',
    'Ranjitha',
    'Rasulgani',
    'Rathi',
    'Rathinam',
    'Ravi',
    'Ravichandran',
    'Ravikumar',
    'Reginabivee',
    'Rengaraj',
    'Revathi',
    'Saber',
    'Sagayaraj',
    'Sagulhameed',
    'Sagunthalan',
    'Sakthivel',
    'Samaiyan',
    'Samikannu',
    'Sankar',
    'Sanmugam',
    'Santhi',
    'Santhiyagu',
    'Saranya',
    'Sarasu',
    'Saravanan',
    'Sarbudeen',
    'Saritha',
    'Saroja',
    'Sasikala',
    'Sathappan',
    'Sathik batcha',
    'Sathish',
    'Sathiya',
    'Savarimuthu',
    'Seakapthulla',
    'Sekar',
    'Sekaran',
    'Sellaiya',
    'Sellaiyan',
    'Sellapa',
    'Selvaganapathi',
    'Selvam',
    'Selvapakiyam',
    'Selvaraj',
    'Selvarani',
    'Selvarasu',
    'Selvi',
    'Sennimalai gounder',
    'Senthilkumar',
    'Senthilnathan',
    'Senthilvadivu',
    'Sethurajan',
    'Shanmugam',
    'Shanmugasundaram',
    'Shiek Abdulla',
    'Sinduja',
    'Singalaxmi',
    'Singaram',
    'Singaravelu',
    'Sithik',
    'Siva',
    'Sivakolundhu',
    'Sivakumar',
    'Sivalingam',
    'Sivaraman',
    'Sivasami',
    'Sivasamy',
    'Sivasankaran',
    'Soakku',
    'Solai',
    'Solaimalai',
    'Sona',
    'Soundararajan',
    'Soundaravalli',
    'Srinivasan',
    'Suba',
    'Subbaiya',
    'Subbaiyan',
    'Subbu',
    'Subramani',
    'Subramanian',
    'Sugumar',
    'Sulochana',
    'Sulthanravuthar',
    'Sumathi',
    'Sundaram',
    'Sundarambal',
    'Surendar',
    'Suresh',
    'Sureshkumar',
    'Suseela',
    'Suthagar',
    'T.S.Neelakandan',
    'Tamilselvi',
    'Thamaraiselvi',
    'Thamayanthi',
    'Thambidurai',
    'Thanapillai',
    'Thangaian',
    'Thangaponnu',
    'Thangaraju',
    'Thangaraju/Selvi',
    'Thangavel',
    'Tharmalingam',
    'Thavuthmeerasa',
    'Theivanai',
    'Thinasmarry',
    'Thirumurugan',
    'Thiyagarajan',
    'Ussain',
    'Utharapathi',
    'Uthayakumari',
    'Vadivel',
    'Vaidhiyalingam',
    'Vairakkannu',
    'Vairavan',
    'Valarmathi',
    'Vanmehanathan',
    'Vasantha',
    'Vasudevan',
    'Vasuki',
    'Veeraian',
    'Veeraiya',
    'Veeralaxmi',
    'Veeramani',
    'Veeramuthu',
    'Veerappan',
    'Veerasamy',
    'Veerasundaram',
    'Velayutham',
    'Vellaichamy',
    'Velmurugan',
    'Veluchamy',
    'Vembaiyan',
    'Vignesh',
    'Vijay',
    'Vijayakumar',
    'Vijayakumari',
    'Vimal',
    'Viman',
    'Vinesh',
    'Viswanathan',
    'Yogamani',
  ];
  itemSet: string[] = [
    'Arainaan kodi',
    'Aram',
    'Baby valayal',
    'Chain',
    'Dollar',
    'Dollar chain',
    'Jimikki',
    'KPS Modhiram',
    'Kai chain',
    'Kal dollar necklace',
    'Kal jimikki',
    'Kal modhiram',
    'Kal mookuthi',
    'Kal necklace',
    'Kal thodu',
    'Kal thodu jimikki',
    'Kal thodu thongal',
    'Kasu',
    'Kasu malai',
    'Kathu valayam',
    'Ku.Thodu',
    'Ma kasu',
    'Mani',
    'Mattal',
    'Meen dollar',
    'Meen dollar chain',
    'Modhiram',
    'Modhiram A',
    'Modhiram N',
    'Muthu thodu',
    'Nanal kulai',
    'Necklace',
    'Nethisutti',
    'Om dollar chain',
    'Pottu',
    'Puli naha dollar',
    'Ring',
    'Saidu mattal',
    'Star thodu',
    'Thali kasu',
    'Thayathu',
    'Thodu',
    'Thodu jimikki',
    'Thodu mattal',
    'Thodu thongal',
    'Thongal',
    'Valayal',
    'Valayam',
    'Yanai mudi ring',
  ];
}
